[package]
name = "dxf_janitors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.16", features = ["derive"] }
dxf = "0.5.0"
svg = "0.10.0"
log = "0.4.14"
env_logger = "0.9.0"